Controllers/TagAdminController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using DreamGames.Database.Context;
using DreamGames.Database.Games;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace dreamgames.Controllers
{
    public class TagAdminController : Controller
    {
        private readonly ContentContext _context;
        public TagAdminController(ContentContext context)
        {
            _context = context;
        }
        // GET: TagAdmin
        public ActionResult Index()
        {
            return View();
        }

        // GET: TagAdmin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: TagAdmin/Create
        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]

        //Creates a tag in the context so it adds a new tag and then saves the changes in the context database.
        public ActionResult CreateTag(Tag taggy)
        {
            
            try
            {
                _context.Tags.Add(taggy);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TagAdmin/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: TagAdmin/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TagAdmin/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: TagAdmin/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/TagAdmin/Index.cshtml
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"
@*@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using DreamGames.Database.Games;
@model Tag

@*View for the TagAdmin controller so we can enter TagName,Slug and RawGTagId
So that we can add new tags through this function instead of manually coding new tags
in the context database.*@

    <form method="post" asp-controller="TagAdmin" asp-action="CreateTag">
        <div><strong>Add tags</strong></div>
        <label for="name">Tag name:</label>
        <input asp-for="@Model.TagName" id="name"/>
        <label for="name">Slug:</label>
        <input asp-for="@Model.Slug" id="slug"/>
        <label for="name">RawG tag ID:</label>
        <input type="text" asp-for="@Model.RawGTagId" id="rawgTagId"/>
        <input type="submit" value="Add"/>
    </form>